### ISSUE TITLE
Arrow edges are hidden by nodes in Graph Cluster View (FruchtermanReingold)

### ISSUE THREAD

**Issue by bingao** [nabil6391/graphview#75] opened 2022-03-29 13:29 UTC
Hi,

First, thank you for the nice package! I tried to use graphview to build directed graph. I first ran the example of this package on macOS (macOS) and Chrome (chrome), and found arrow edges are hidden by nodes in Graph Cluster View (FruchtermanReingold), as shown in the screenshot.

<img width="1088" alt="Screenshot 2022-03-29 at 15 22 38" src="https://user-images.githubusercontent.com/1943119/160621458-cbea3f80-ed51-4afe-bda2-8f3a29407d69.png">

Do you know what the problem could be? How can I fix it? Thank you.

**Comment by nabil6391** [comment] 2023-04-29 10:31
Duplicate of #62

**Closed by nabil6391** 2023-04-29 10:31 UTC
Labels: bug
