### ISSUE TITLE
Layered Graph can't display Loops

### ISSUE THREAD

**Issue by h80r** [nabil6391/graphview#82] opened 2022-05-15 22:29 UTC
I was trying to display an NFA-ε which required the edge of a grandchild to go back into it's grandparent node.
Using SugiyamaAlgorithm the resulting graph isn't correct, as visible on the attached image.

![image](https://user-images.githubusercontent.com/60087690/168496546-4df45328-23c7-42b0-81ba-b9527c4c0603.png)

Node `q2` should have an edge to node `q1`, instead node `q1` has a strange edge to itself.

**Comment by nabil6391** [comment] 2022-05-16 01:59
Can you share what would be the correct UI ? Sugiyama graph does not allow loops.

**Comment by h80r** [comment] 2022-05-16 09:38
I wanted to create something similar to this graph:
![image](https://user-images.githubusercontent.com/60087690/168564150-a761a11d-4f1f-4084-b2b4-09c2d64b5464.png)

**Comment by nabil6391** [comment] 2022-05-21 16:43
Unfortunately not possible with the current implementation.

**Comment by nabil6391** [comment] 2023-04-29 11:36
Duplicate of #79

**Closed by nabil6391** 2023-04-29 11:36 UTC
